### ISSUE TITLE
Runtime error,core dumped

### ISSUE THREAD

**Issue by yufengsjtu** [iitkcpslab/GAMRCPP#1]
Hello author,i would like to ask a question about running your code.When i try to run the project as you described in the readme file,a core dumped error occurred in the gamrcppMainExecutable node as i started the second start_robots node,how can i solve this problem?

**Comment by RatijitMitra** [comment]
Hi, please ensure that you have run the following two commands for the example given -
rosrun gamrcpp_pkg gamrcppMainExecutable _ws_x:=4 _ws_y:=3 _rc:=2 (mentioned in instruction 4 > Tab 2)
rosrun gamrcpp_pkg start_robots 2 (mentioned in instruction 4 > Tab 3).
