### ISSUE TITLE
some puzzle about the algorithm

### ISSUE THREAD

**Issue by ghost** [iitkcpslab/GAMRCPP#2]
Hi,please allow me to take a few minutes of your time.I would like to know if considering the sensor radius,we only use the perception radius to fully cover every grid,rather than the robot itself accessing every grid,can this algorithm still work?

**Comment by RatijitMitra** [comment]
It will work, provided you make the appropriate code changes as needed. E.g., updateLocalView() at line 157 in src/robot.cpp marks a cell as covered when a robot passes through it (line 167). You need to mark a cell as covered if it is within the sensing radius. So, please go ahead and update that function accordingly.
